// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	ID         uuid.UUID        `json:"id"`
	UserID     string           `json:"user_id"`
	Type       string           `json:"type"`
	CreditCost *int32           `json:"credit_cost"`
	Status     string           `json:"status"`
	Progress   int32            `json:"progress"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
