// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const updateVideoProgress = `-- name: UpdateVideoProgress :exec
UPDATE video
SET progress = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateVideoProgressParams struct {
	Progress int32     `json:"progress"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVideoProgress(ctx context.Context, arg UpdateVideoProgressParams) error {
	_, err := q.db.Exec(ctx, updateVideoProgress, arg.Progress, arg.ID)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE video
SET status = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateVideoStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus, arg.Status, arg.ID)
	return err
}
